chunk_size: 500
data_path: help_mail_ru.pkl
db_path: db
embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
llm_model: llama-3.1-8b-instant
overlap: 100
retrieval_top_k: 6
seed: 42
temperature: 0
